name: Marketplace Test

on:
  workflow_dispatch:

jobs:
  test-action-job-win32:
    runs-on: windows-latest
    name: kube-score (Win32)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: kube-score action step
        uses: piraces/kube-score-ga@v0.1.2
        with:
          manifests-folders: './sample-manifests/sample-manifests/*.yaml,./sample-manifests/sample-policy-manifest/*.yaml'
          ignore-exit-code: 'true'
          output-file: 'output.txt'
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-1
          path: output.txt

  test-action-job-linux:
    runs-on: ubuntu-latest
    name: kube-score (Linux)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: kube-score action step
        uses: piraces/kube-score-ga@v0.1.2
        with:
          manifests-folders: './sample-manifests/sample-manifests/*.yaml,./sample-manifests/sample-policy-manifest/*.yaml'
          ignore-exit-code: 'true'
          kube-score-version: '1.14.0'
          output-file: 'output.txt'
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-2
          path: output.txt

  test-action-job-macos:
    runs-on: macos-latest
    name: kube-score (MacOS)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: kube-score action step
        uses: piraces/kube-score-ga@v0.1.2
        with:
          manifests-folders: './sample-manifests/sample-manifests/*.yaml,./sample-manifests/sample-policy-manifest/*.yaml'
          ignore-exit-code: 'true'
          kube-score-version: '1.14.0'
          output-file: 'output.txt'
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-3
          path: output.txt
