name: Action CI

on: [push]

jobs:
  test-action-job-win32:
    runs-on: windows-latest
    name: kube-score (Win32)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: kube-score action step
        uses: ./ # Uses an action in the root directory
        id: ksga
        with:
          manifests-folders: './sample-manifests/sample-manifests/*.yaml,./sample-manifests/sample-policy-manifest/*.yaml'
          ignore-exit-code: 'true'

  test-action-job-linux:
    runs-on: ubuntu-latest
    name: kube-score (Linux)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: kube-score action step
        uses: ./ # Uses an action in the root directory
        id: ksga
        with:
          manifests-folders: './sample-manifests/sample-manifests/*.yaml,./sample-manifests/sample-policy-manifest/*.yaml'
          ignore-exit-code: 'true'
          kube-score-version: '1.8.0'

  test-action-job-macos:
    runs-on: macos-latest
    name: kube-score (MacOS)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: kube-score action step
        uses: ./ # Uses an action in the root directory
        id: ksga
        with:
          manifests-folders: './sample-manifests/sample-manifests/*.yaml,./sample-manifests/sample-policy-manifest/*.yaml'
          ignore-exit-code: 'true'
          kube-score-version: '1.8.0'
