on: [push]

jobs:
  test-action-job-win32:
    runs-on: windows-latest
    name: A job to test kube-score Github Action (Win32)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: kube-score action step
        uses: ./ # Uses an action in the root directory
        id: ksga
        with:
          manifests-folders: './test/sample-manifests/*.yaml,./test/sample-policy-manifest/*.yaml'
      - name: Get the total score from the action
        run: echo "The total score was ${{ steps.ksga.outputs.score }}"
      - name: Get the raw output from kube-score
        run: echo "The raw output was ${{ steps.ksga.outputs.raw-output }}"

  test-action-job-linux:
    runs-on: ubuntu-latest
    name: A job to test kube-score Github Action (Linux)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: kube-score action step
        uses: ./ # Uses an action in the root directory
        id: ksga
        with:
          manifests-folders: './test/sample-manifests/*.yaml,./test/sample-policy-manifest/*.yaml'
      - name: Get the total score from the action
        run: echo "The total score was ${{ steps.ksga.outputs.score }}"
      - name: Get the raw output from kube-score
        run: echo "The raw output was ${{ steps.ksga.outputs.raw-output }}"

  test-action-job-macos:
    runs-on: macos-latest
    name: A job to test kube-score Github Action (MacOS)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: kube-score action step
        uses: ./ # Uses an action in the root directory
        id: ksga
        with:
          manifests-folders: './test/sample-manifests/*.yaml,./test/sample-policy-manifest/*.yaml'
      - name: Get the total score from the action
        run: echo "The total score was ${{ steps.ksga.outputs.score }}"
      - name: Get the raw output from kube-score
        run: echo "The raw output was ${{ steps.ksga.outputs.raw-output }}"
